<?php print  $this->doctype() ?>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="dsin-skeleton-app">
    <meta name="author" content="Bruno F. C. Silva">
    <link rel="shortcut icon" href="/img/favicon.png">

    <title>DSIN Skeleton App</title>

    <!-- Bootstrap core CSS -->
    <!-- build:css /vendor/bootstrap/css/bootstrap.min.css -->
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- endbuild -->
    <!-- build:css /css/app.min.css -->
    <link href="/vendor/dynatable/jquery.dynatable.css" rel="stylesheet">
    <link href="/vendor/nProgress/nProgress.css" rel="stylesheet">
    <link href="/vendor/yamm3/yamm.css" rel="stylesheet">
    <link href="/css/app.css" rel="stylesheet">
    <!-- endbuild -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">DSIN App Skeleton</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


      <div class="container">

        <form id="loginForm" class="form-signin" role="form" style="max-width: 320px;" action="autenticacao/login" method="post" novalidate parsley-validate>
          <input type="hidden" name="method" value="POST">        
          <h2 class="form-signin-heading">Please sign in</h2>
          <input type="email"    id="field_usuario" name="usuario" class="form-control" placeholder="Email address" autofocus required>
          <input type="password" id="field_senha"   name="senha"   class="form-control" placeholder="Password" required>

          <button id="btnLogin" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
          <br>
          <p class="text-center">This is the DSIN Skeleton app</p>
      
          <div id="formMessages" class="container"></div>
        </form>

      </div> <!-- /container -->
      </div>

    <!-- build:js http://code.jquery.com/jquery-2.1.0.min.js -->
    <script src="http://code.jquery.com/jquery-2.1.0.js"></script>
    <!-- endbuild -->
    <!-- build:js /vendor/bootstrap/js/bootstrap.min.js -->
    <script src="/vendor/bootstrap/js/bootstrap.js"></script>
    <!-- endbuild -->
    <!-- build:js /vendor/nProgress/nProgress.min.js -->
    <script src="/vendor/nProgress/nProgress.js"></script>
    <!-- endbuild -->
    <!-- build:js /js/app.min.js -->
    <script src="/js/app.js"></script>
    <!-- endbuild -->
    <!-- build:js /vendor/parsley/parsley.all.min.js -->
    <script src="/vendor/parsley/parsley.js"></script>
    <script src="/vendor/parsley/parsley.extend.js"></script>
    <!-- endbuild -->

    <script type="text/javascript">
    (function() {

      // Prepara Validação do Formulario
      $("#field_usuario").attr("parsley-required-message"  , "E-mail é obrigatório"  );
      $("#field_usuario").attr("parsley-type-email-message", "E-mail Inválido"       );
      $("#field_senha").attr("parsley-required-message"    , "Password é obrigatório");

      $('#loginForm').parsley( {
         errors: {
            container: function (element, isRadioOrCheckbox) {
                var $container = $("#formMessages");
                if ($container.length === 0) {
                    $container = $("<div id='' class='parsley-container'></div>").insertBefore(element);
                }
                return $container;
            }
        }
      });

      // Prepara a ação dos botoes
      $("#btnLogin").click(function(event) {
          $("#fieldMethod").val("POST");
      });

      DSINConnect.attachToForm({
            formID: '#loginForm',
            messagesContainer: '#formMessages'
      });

    })();
    </script>
  </body>
</html>