<?php print  $this->doctype() ?>
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="dsin-skeleton-app">
	<meta name="author" content="Bruno F. C. Silva">
	<link rel="shortcut icon" href="/img/favicon.png">

	<title>Relatório</title>

	<!-- CSS -->
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
	<style type="text/css">

/*
 * -- BASE STYLES --
 * Most of these are inherited from Base, but I want to change a few.
 */

/*
 * -- Layout Styles --
 */
.l-content {
    margin: 0 auto;
}


/*
 * -- BANNER --
 * The top banner with the headings. By using a combination
 * of `display: table;` and `display: table-cell;`, we can
 * vertically center the text.
 */

.banner {
    text-align: center;
    width: 100%;
}

    .banner-head {
        vertical-align: middle;
        font-size: 2em;
    }




.footer {
    background: #111;
    color: #888;
    text-align: center;
}
    .footer a {
        color: #ddd;
    }
.footer p {
	maring:0;
}



	</style>
	<!-- <link href="/css/app.css" rel="stylesheet" medial="all"> -->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	  <![endif]-->
	</head>

	<body>
		<div class="banner">
    <h1 class="banner-head">
        Header Here
    </h1>
</div>
			<div class="l-content">

		<table class="pure-table" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
        </tr>
    </thead>

    <tbody>
        <tr class="pure-table-odd">
            <td>1</td>
            <td>Honda</td>
            <td>Accord</td>
            <td>2009</td>
        </tr>

        <tr>
            <td>2</td>
            <td>Toyota</td>
            <td>Camry</td>
            <td>2012</td>
        </tr>

        <tr class="pure-table-odd">
            <td>3</td>
            <td>Hyundai</td>
            <td>Elantra</td>
            <td>2010</td>
        </tr>

        <tr>
            <td>4</td>
            <td>Ford</td>
            <td>Focus</td>
            <td>2008</td>
        </tr>

        <tr class="pure-table-odd">
            <td>5</td>
            <td>Nissan</td>
            <td>Sentra</td>
            <td>2011</td>
        </tr>

        <tr>
            <td>6</td>
            <td>BMW</td>
            <td>M3</td>
            <td>2009</td>
        </tr>

        <tr class="pure-table-odd">
            <td>7</td>
            <td>Honda</td>
            <td>Civic</td>
            <td>2010</td>
        </tr>

        <tr>
            <td>8</td>
            <td>Kia</td>
            <td>Soul</td>
            <td>2010</td>
        </tr>
    </tbody>
</table>

			</div> <!-- /container -->
<br>			
<div class="footer">
    <p>
        <button onclick="window.print();" class="pure-button pure-button-primary">Print</button> Footer Here
    </p>
</div>			

	</body>
</html>