<?php print  $this->doctype() ?>
<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="dsin-skeleton-app">
	<meta name="author" content="Bruno F. C. Silva">
	<link rel="shortcut icon" href="/img/favicon.png">

	<title>DSIN Skeleton App</title>

	<!-- CSS -->
    <!-- build:css /vendor/bootstrap/css/bootstrap.min.css -->
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- endbuild -->
    <!-- build:css /css/app.min.css -->
	<link href="/vendor/dynatable/jquery.dynatable.css" rel="stylesheet">
	<link href="/vendor/nProgress/nProgress.css" rel="stylesheet">
	<link href="/vendor/yamm3/yamm.css" rel="stylesheet">
	<link href="/css/app.css" rel="stylesheet">
	<!-- endbuild -->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	  <![endif]-->
	</head>

	<body>

		<!-- Fixed navbar -->
		<div class="navbar yamm navbar-default navbar-fixed-top" role="navigation" id="menu2">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">DSIN App Skeleton</a>
				</div>
				<div id="navbar-collapse-1" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<?php

						function existeSubMenu($menu, $subMenus) {
							if(isset($subMenus[$menu]))
								return true;

							return false;
						}

						function printSubMenu($subMenu, $allSubMenus) {
							print '<li class="dropdown-submenu">';
							print '<a tabindex="-1" href="#">' . $subMenu['CDMNUNOME'] . '</a>';
							print '<ul class="dropdown-menu">';

							foreach($allSubMenus[$subMenu['CDMNUMENU']] as $sm) {

								switch($sm['CDMNUTIPO']) {
									case 0:
									print '<li><a tabindex="-1" href="#" onclick="openModal(\'/' . $sm['CDMNUMENU'] . '\', \'#mainAppContainer\')">' . $sm['CDMNUNOME'] . '</a></li>';
									break;

									case 1:
									echo '<li role="presentation" class="divider"></li>';
									break;

									case 2:
									echo '<li role="presentation" class="dropdown-header">' . $sm['CDMNUNOME'] . '</li>';
									break;
								}

								if(existeSubMenu($sm['CDMNUMENU'], $allSubMenus))
									printSubMenu($sm, $allSubMenus);

							}
							print '</ul>';
						}

						foreach($this->menusPrincipais as $key => $menu) {

						?>
							<!-- Classic dropdown -->
							<li class="dropdown">
								<?php
				  				// verifica se o menu principal tem submenu
								if(isset($this->subMenus[$menu['CDMNUMENU']]) && count($this->subMenus[$menu['CDMNUMENU']]) > 0) {
								?>
									<a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo $menu['CDMNUNOME']; ?><b class="caret"></b></a>

									<ul role="menu" class="dropdown-menu">

									<?php
									foreach($this->subMenus[$menu['CDMNUMENU']] as $subMenu) {

										if(!existeSubMenu($subMenu['CDMNUMENU'], $this->subMenus)) {

											switch($subMenu['CDMNUTIPO']) {
												case 0:
												print '<li><a tabindex="-1" href="#" onclick="openModal(\'/' . $subMenu['CDMNUMENU'] . '\', \'#mainAppContainer\')">' . $subMenu['CDMNUNOME'] . '</a></li>';
												break;

												case 1:
												echo '<li role="presentation" class="divider"></li>';
												break;

												case 2:
												echo '<li role="presentation" class="dropdown-header">' . $subMenu['CDMNUNOME'] . '</li>';
												break;
											}

										// Existe SubMenu
										} else {

											printSubMenu($subMenu, $this->subMenus);

						  				} // Final Existe Submenu
					  				} // for submenu
					  				?>
									</ul>
								<?php
				  				// Menu Principal nao tem submenu
								} else {
								?>
									<a href="#" data-toggle="dropdown" class="dropdown-toggle" onclick="openModal('/<?php echo $menu['CDMNUMENU']; ?>', '#mainAppContainer')"><?php echo $menu['CDMNUNOME']; ?></b></a>
								<?php
				  				} // Menu Principal tem ou nao menu
				  				?>
							</li>
						<?php 
			  			} // foreach Menu
			  			?>
					</ul>
					<p class="navbar-text">Automatic Generated</p>
					<button type="button" class="btn btn-default navbar-btn" onclick="$('#menu1').toggleClass('hidden');$('#menu2').toggleClass('hidden');">Change Menu Style</button>
				</div>
			</div>
		</div>

		<!-- Fixed navbar -->
		<div class="navbar yamm navbar-default navbar-fixed-top hidden" role="navigation" id="menu1">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">DSIN App Skeleton</a>
				</div>
				<div id="navbar-collapse-1" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<!-- Classic list -->
						<li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Sistema<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<!-- Content container to add padding -->
									<div class="yamm-content">
										<div class="row">
											<ul class="col-md-5 list-unstyled mnuBorder">
												<li>
													<p><strong>Manutenção</strong></p>
												</li>
												<li><a href="#"> Dados Departamento </a></li>
												<li><a href="#"> Suporte </a></li>
												<li><a href="#"> Sobre </a></li>
												<li><a href="#"> Sair </a></li>
											</ul>
											<ul class="col-md-4 list-unstyled">
												<li>
													<p><strong>Controle Acesso</strong></p>
												</li>
												<li><a href="#"> Grupo </a></li>
												<li><a href="#"> Usuário </a></li>
												<li><a href="#"> Autorizações </a></li>
											</ul>
											<ul class="col-md-3 list-unstyled">
											</ul>
										</div>
									</div>
								</li>
							</ul>
						</li>

						<!-- Classic list -->
						<li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Protocolo<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<!-- Content container to add padding -->
									<div class="yamm-content">
										<div class="row">
											<ul class="col-md-6 list-unstyled mnuBorder">
												<li>
													<p><strong>Credencial</strong></p>
												</li>
												<li><a href="#"> Nova </a></li>
												<li><a href="#"> Renovação </a></li>
												<li><a href="#"> Baixa / Suspensão / Cassação </a></li>
											</ul>
											<ul class="col-md-4 list-unstyled">
												<li>
													<p><strong>Impressão</strong></p>
												</li>
												<li><a href="#"> Credencial </a></li>
												<li><a href="#"> Requerimento </a></li>
												<li><a href="#"> Legislação </a></li>
											</ul>
											<ul class="col-md-3 list-unstyled">
											</ul>
										</div>
									</div>
								</li>
							</ul>
						</li>

						<!-- Classic list -->
						<li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Consulta</b></a>
						</li>

						<!-- Classic list -->
						<li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Relatórios<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<!-- Content container to add padding -->
									<div class="yamm-content">
										<div class="row">
											<ul class="col-md-6 list-unstyled mnuBorder">
												<li>
													<p><strong>Listagens</strong></p>
												</li>
												<li><a href="#"> Credenciais Suspensas / Caçadas </a></li>
												<li><a href="#"> Benefisiários Ativos / Inativos </a></li>
											</ul>
											<ul class="col-md-5 list-unstyled">
												<li>
													<p><strong>Gerencial</strong></p>
												</li>
												<li><a href="#"> Resumo Geral de Utilização </a></li>
											</ul>
											<ul class="col-md-3 list-unstyled">
											</ul>
										</div>
									</div>
								</li>
							</ul>
						</li>
					</ul>
					<p class="navbar-text">Hand made Menu</p>
					<button type="button" class="btn btn-default navbar-btn" onclick="$('#menu1').toggleClass('hidden');$('#menu2').toggleClass('hidden');">Change Menu Style</button>
				</div>
				
				<!-- <div class="navbar-collapse collapse">
				  
				  
				  
				  
				  
				  <ul class="nav navbar-nav">
					<li class="active"><a href="#" onclick="openModal('Cadastro Exemplo', '/opcCadTeste', '#mainAppContainer')">Cadastro Exemplo</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="autenticacao/logout">Logout</a></li>
				  </ul>
				  <p class="navbar-text">Logged in as: <?php echo $this->usuario; ?></p>
				</div> -->
			</div>
		</div>


		<div id="mainAppContainer">
			<div class="container theme-showcase">

				<!-- Main jumbotron for a primary marketing message or call to action -->
				<div class="jumbotron">
					<h1>Hello, world!</h1>
					<p>This is the DSIN App Skeleton.</p>
				</div>

			</div> <!-- /container -->

			<div class="baseToModal"><div class="modal fade"></div></div>
		</div>

	    <!-- build:js http://code.jquery.com/jquery-2.1.0.min.js -->
	    <script src="http://code.jquery.com/jquery-2.1.0.js"></script>
	    <!-- endbuild -->
	    <!-- build:js /vendor/bootstrap/js/bootstrap.min.js -->
	    <script src="/vendor/bootstrap/js/bootstrap.js"></script>
	    <!-- endbuild -->
	    <!-- build:js /vendor/parsley/parsley.min.js -->
	    <script src="/vendor/parsley/parsley.js"></script>
	    <!-- endbuild -->
	    <!-- build:js /vendor/parsley/parsley.extend.min.js -->
	    <script src="/vendor/parsley/parsley.extend.js"></script>
	    <!-- endbuild -->
	   	<!-- build:js /vendor/dynatable/jquery.dynatable.min.js -->
		<script src="/vendor/dynatable/jquery.dynatable.js"></script>
		<!-- endbuild -->
	    <!-- build:js /vendor/nProgress/nProgress.min.js -->
	    <script src="/vendor/nProgress/nProgress.js"></script>
	    <!-- endbuild -->
		<!-- build:js /vendor/meiomask/meiomask.min.js -->
		<script src="/vendor/meiomask/meiomask.js"></script>
		<!-- endbuild -->
		<!-- build:js /js/app.min.js -->
		<script src="/js/app.js"></script>
		<script src="/vendor/dsinmessagebox/dsinMessageBox.js"></script>
		<!-- endbuild -->

	</body>
</html>